#!/bin/bash

## set -x

CWD=/Users/henk/git/harmony-ng
HA=homeassistant.local
APPDIR=/addon_configs/a0d7b954_appdaemon/apps/harmony-ng
ESPDIR=/config/esphome

cd $CWD || exit

rm -rf x_old
mv -f x x_old
mkdir x
cd x
mkdir appdaemon	esphome

rsync -e ssh -a $HA:$APPDIR/harmony.py appdaemon
rsync -e ssh -a $HA:$APPDIR/devices appdaemon

rsync -e ssh -a $HA:$ESPDIR/common esphome
#rsync -e ssh -a $HA:$ESPDIR/living-room-gw.yaml esphome
rsync -e ssh -a $HA:$ESPDIR/tv-room-gw.yaml esphome

rm -rf appdaemon/*/__pycache__
rm -f appdaemon/devices/{pi6,pia,xx}

for i in $(find . -type f)
do
	cmp $i ../app/$i > /dev/null && rm -f $i
done

find . -type f | sort
