binary_sensor:
  - platform: remote_receiver
    receiver_id: receiver_rf
    internal: true
    name: "RC6 OK"
    rc6:
      address: 0
      command: 0x5c
    on_press:
      - button.press: pan_pwr
