remote_receiver:
# WORKS - IR
#    pin:
#      number: GPIO23
#      inverted: True
#    tolerance: 30%
#    filter: 500us - SONY, JVC, LG, NEC, PIONEER
#    filter: 400us - PANASONIC
#    filter: 300us - PANASONIC/DENON
#    idle: DEFAULT
#    buffer_size: 2kb
  - id: receiver_ir
    pin:
      number: GPIO23
      inverted: True
#    tolerance: 30%
    filter: 400us
#    memory_blocks: 8
#    idle: 4ms
#    buffer_size: 2kb
#    dump: all
    dump:
    - abbwelcome
    - aeha
    - byronsx
    - canalsat
    - canalsatld
    - coolix
    - dish
    - dooya
    - drayton
    - jvc
    - keeloq
    - haier
    - lg
    - magiquest
    - midea
    - nec
    - nexa
    - panasonic
    - pioneer
#    - pronto
#    - raw
    - rc5
    - rc6
    - rc_switch
    - roomba
    - samsung
    - samsung36
    - sony
    - toshiba_ac
    - mirage
    on_sony:
      then:
      - homeassistant.event:
          event: esphome.receiver_ir
          data_template: 
            rcv: "IR - SONY"
            data: !lambda "return x.data;"
            nbits: !lambda "return x.nbits;"
#    on_panasonic:
#      then:
#      - homeassistant.event:
#          event: esphome.receiver_ir
#          data_template: 
#            rcv: "IR - PANA"
#            command: !lambda "return x.command;"
#           address: !lambda "return x.address;"
#    on_rc6:
#      then:
#      - homeassistant.event:
#          event: esphome.receiver_ir
#          data_template: 
#            rcv: "IR - RC6"
#            command: !lambda "return x.command;"
#            address: !lambda "return x.address;"
