binary_sensor:
  - platform: remote_receiver
    receiver_id: receiver_rf
    internal: true
    name: "RC6 Vol+"
    rc6:
      address: 1
      command: 0x10
    on_press:
      - button.press: denon_vol_up
      - delay: !lambda "return 5;"
      - button.press: denon_vol_up
  - platform: remote_receiver
    receiver_id: receiver_rf
    internal: true
    name: "RC6 Vol-"
    rc6:
      address: 1
      command: 0x11
    on_press:
      - button.press: denon_vol_down
      - delay: !lambda "return 5;"
      - button.press: denon_vol_down
