binary_sensor:
  - platform: remote_receiver
    receiver_id: receiver_rf
    internal: true
    name: "RC6 Vol+"
    rc6:
      address: 0
      command: 0x10
    on_press:
      - button.press: denon_paup
      - delay: !lambda "return 1;"
      - button.press: denon_paup
  - platform: remote_receiver
    receiver_id: receiver_rf
    internal: true
    name: "RC6 Vol-"
    rc6:
      address: 0
      command: 0x11
    on_press:
      - button.press: denon_padn
      - delay: !lambda "return 1;"
      - button.press: denon_padn
